// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GraphvizVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "GraphvizVS.7e008693-51b2-4c63-9a07-b7d03e14965e";
        public const string Name = "GraphvizVS";
        public const string Description = @"Streamline your Graphviz graph creation in Visual Studio with GraphvizVS; instantly preview and export diagrams with added IntelliSense support for quicker editing.";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Amadej Glasenčnik";
        public const string Tags = "graphviz, visual-studio, tools, graphs, vsix, dot-language";
    }
}
