// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GraphvizVS
{
    internal sealed partial class Vsix
    {
        public const string Id = "GraphvizVS.7e008693-51b2-4c63-9a07-b7d03e14965e";
        public const string Name = "GraphvizVS";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Amadej Glasenčnik";
        public const string Tags = "";
    }
}
