// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace GraphvizVS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string uiContextSupportedFilesString = "0dffcf6f-b73d-43bb-b692-eee5d95dc18e";
        public static Guid uiContextSupportedFiles = new Guid(uiContextSupportedFilesString);

        public const string GraphvizVSString = "0dffcf6f-b73d-43bb-b692-eee5d95dc18e";
        public static Guid GraphvizVS = new Guid(GraphvizVSString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int GraphvizMenuGroup = 0x1100;
        public const int ExportGraphCommand = 0x0100;
        public const int OpenGraphPreviewWindowCommand = 0x0200;
    }
}